# Dependencies
markdown:         kramdown
highlighter:      pygments
excerpt_separator: ""

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Manoj Awasthi'
tagline:          ''
description:      'Autodidact.'
url:              https://awmanoj.github.io
baseurl:          /

author:
  name:           'Manoj Awasthi'
  url:            https://twitter.com/awmanoj

paginate:         5

google_analytics: UA-82105506-1
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/awmanoj/awmanoj.github.io
